version: '3.8'

services:
  db:
    image: postgres:13.6
    restart: always
    container_name: 'postgres'
    environment:
        POSTGRES_PASSWORD: 'blockscout'
        POSTGRES_USER: 'blockscout'
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - blockscout

  blockscout:
    depends_on:
      - db
    image: blockscout/blockscout:${DOCKER_TAG:-latest}
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
      args:
        COIN: "EDGE"
    restart: always
    container_name: 'blockscout'
    command: 'mix do ecto.create, ecto.migrate, phx.server'
    env_file:
      -  ./envs/common-blockscout.env
    ports:
      - 4000:4000
    networks:
      - blockscout

networks:
  blockscout:
volumes:
  db-data:

